package com.gabriel_barros.controle_entregua_agua.ui

 val names = mapOf(
    "18" to 0L,
    "176" to 1L,
    "184" to 2L,
    "210" to 3L,
    "212" to 4L,
    "224" to 5L,
    "237" to 6L,
    "ademar" to 7L,
    "André piteira" to 8L,
    "anselmo" to 9L,
    "antonio" to 10L,
    "bosh" to 11L,
    "cachorra vivi" to 12L,
    "cambel" to 13L,
    "Conceição " to 14L,
    "cristina" to 15L,
    "delmira loja" to 16L,
    "dionybe." to 17L,
    "eliane " to 18L,
    "felipe" to 19L,
    "frank" to 20L,
    "gorete" to 21L,
    "gráfica" to 22L,
    "hilma" to 23L,
    "iolete " to 24L,
    "ismar" to 25L,
    "isnaudem" to 26L,
    "joca amanda" to 27L,
    "junior dentadura" to 28L,
    "larissa" to 29L,
    "leandro moto" to 30L,
    "ligia" to 31L,
    "lucinha" to 32L,
    "luis henrique" to 33L,
    "madalena canto j. dent" to 34L,
    "mãe de elizangela" to 35L,
    "marcio" to 36L,
    "marise" to 37L,
    "marly " to 38L,
    "marta " to 39L,
    "marujo" to 40L,
    "mirante" to 41L,
    "onorio" to 42L,
    "quadrangular" to 43L,
    "Rafael " to 44L,
    "renan" to 45L,
    "roberto socorro" to 46L,
    "rosangela" to 47L,
    "sergio " to 48L,
    "silvia" to 49L,
    "simoa" to 50L,
    "socorro" to 51L,
    "testemunho" to 52L,
    "vava" to 53L,
    "xareu" to 54L,
    "113 gaiola" to 55L,
    "fabio " to 56L,
    "João " to 57L,
    "josane" to 58L,
    "luciano " to 59L,
    "neto gráfica " to 60L,
    "Rômulo dentista" to 61L,
    "senhorinha" to 62L,
    "filho de Fábio"  to 63L
)